# Quarkus will choose application.yaml over application.properties.
quarkus:
  http:
    port: 8080
    read-timeout: 30m
    limits:
      max-body-size: 500M

  package:
    uber-jar: true

  # Logging (disable console on prod)
  log:
    level: INFO
    category:
      "org.commonjava.service.tracking":
        level: DEBUG
    console:
      level: DEBUG
      enable: true
    file:
      enable: true
      path: "log/tracking.log"
      level: DEBUG
      format: "%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n"
      rotation:
        max-backup-index: 5
        max-file-size: 10M
  keycloak:
    policy-enforcer:
      enable: false
  oidc:
    enabled: true
    auth-server-url: "https://localhost:8543/realms/indy"
    client-id: indy
    credentials:
      secret: secret
    tls:
      verification: none
    token:
      issuer: any
  security:
    auth:
      enabled-in-dev-mode: false

  oidc-client:
    auth-server-url: "keycloak_server_url/realms/pncredhat"
    client-id: your_client_id
    credentials:
      secret: your_secret

  swagger-ui:
    always-include: true

indy_security:
  enabled: false
  security_bindings_yaml: config/security-bindings.yaml

tracking:
  baseDir: "data"

kafka:
  bootstrap:
    servers: "localhost:9092"

cassandra:
  enabled: true
  host: localhost
  port: 9042
  user: cassandra
  pass: cassandra
  keyspace: folo
  keyspaceReplicas: 1

"%dev":
  quarkus:
    kubernetes-config:
      enabled: false
    log:
      level: INFO
      category:
        "org.commonjava.service.tracking":
          level: TRACE
      console:
        enable: true
      file:
        enable: true
        path: "/tmp/indy-tracking-service.log"
        format: "%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n"
        rotation:
          max-backup-index: 5
          max-file-size: 10M
  tracking:
    baseDir: "data"
    track:
      group:
        content: true

  kafka:
    bootstrap:
      servers: "localhost:9092"

  mp:
    messaging:
      emitter:
        # the default buffer size for emitter's OnOverflow buffer strategy of back-pressure control
        default-buffer-size: 1024
      incoming:
        file-event-in:
          connector: smallrye-kafka
          topic: file-event
          value:
            deserializer: org.commonjava.event.file.FileEventDeserializer
        promote-event-in:
          connector: smallrye-kafka
          topic: promote-complete
          value:
            deserializer: org.commonjava.service.metadata.handler.PathsPromoteCompleteEventDeserializer
